version: '3.8'
services:
  mongo:
    image: mongo:6.0.3
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - mongo:/data
volumes:
  mongo: