version: '3.8'
services:
  mongo:
    image: mongo:6.0.3
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - mongo:/data
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: exarootmple
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  broker:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6380:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - broker:/data
volumes:
  mongo:
  broker:
    driver: local